In [1]:
from numpy import *
from py2boost_test import *

In [2]:
a = arange(12).reshape((3,4))
b = arange(24).reshape((2,3,4))

In [3]:
print(a)
print()
print(a.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [4]:
print(a2s(a))
print(a2s(a.transpose()))

  0  1  2  3
  4  5  6  7
  8  9 10 11

  0  4  8
  1  5  9
  2  6 10
  3  7 11



In [5]:
c = b.transpose((1,0,2))
print(c)
print()
print(a3s(c))

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

  0  1  2  3
 12 13 14 15

  4  5  6  7
 16 17 18 19

  8  9 10 11
 20 21 22 23


